datasets:
  scienceqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/scienceqa_train.json
        val:
          storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/scienceqa_val.json
        test:
          storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/scienceqa_test.json
      images:
        storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/images/
        train:
          storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/images/
        val:
          storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/images/
        test:
          storage: /mnt/HDD2/aiden/InstructBLIP_PEFT/lavis/configs/datasets/scienceqa/input/scienceqa/images/
